### PR TITLE
Feature: hash-based routes (and more!)

### PR DESCRIPTION
**Pull request by pateketrueke**
> Background: the built-in routing mechanism on `svero` did not fullfil the requirements for both nested/hashed routes. I had to research and test if existing libraries could help on this... as I didn't found anything small and useful I just rolled [a module](https://www.npmjs.com/package/abstract-nested-router) for it.

New keywords were introduced and also the ability of nesting `<Router />` components:

```html
<main>
  <Router>
    <Route fallback path="*"><h1>Not found</h1></Route>
    <Route exact path="/" component={Index} />
    <Route path="/company" redirect="/about" />
    <Route path="/about" component={About} />
    <Route path="/user/:name/:age" component={User} />
    <Route path="/admin-false" condition={false} component={User} redirect="/" />
    <Route path="/admin-true" condition={true} component={User} redirect="/" />
    <Route path="/slot"><h3>It works!</h3></Route>
    <Router nofallback path="/nested">
      <Route>
        <a href="#abc/def/ghi">Show params</a> | <Link href="#test">Static test</Link> | <Link href="#">Reset hash</Link>
        <p>
          <Route path="#:any/*path" let:router>Params: {JSON.stringify(router.params)}</Route>
          <Route path="#test">Static placeholder is shown</Route>
          <Route path="#">No hash is present</Route>
        </p>
      </Route>
    </Router>
    <Route path="#*" let:router>
      <p><b>Anchored</b>. {router.params._}</p>
    </Route>
  </Router>
</main>
```

- Use the `nofallback` prop for telling `<Router />` to disable the _fallback_ mechanism from below
- Any route using the `fallback` prop will catch unmatched routes or potential look-up errors, is not the same as `*` and probably is better to always set a _fallback_ somewhere
- Use the `exact` prop to skip this route from render just in case it does not matches, all other routes will render in cascade
- Multiple calls for `/user/:name` and `/user/:name/:age` are not longer required if they share the same context, navigating to `/user` will also render `User` as side-effect (?)
- The `<Route />` without `path` is used for render when the `<Router />` is active

> I did not explored too much the integration details, please let me know if this is fine or I'm missing anything else. (?)

I hope you like it! 🍻

### CODE REVIEW

**Comment by kazzkiq** [comment]
Since the idea is to implement nested routes at some point in the future, I'm not sure it's a nice idea to implement hash-based routes, which could mess with nested implementation.

I also believe that all solutions hash-based routes solve are also solved by nested routes, so they will be eventually replaced even if we implement them now.

**Comment by pateketrueke** [comment]
I would like to see if we can build nested-routes on top of this impl.

We can work later on `handlePopState()` to get rid of `hash` vs `pathname` and make it more robust to handle nested-routes as they deserve a different treatment.

That hash-based stuff can be still doable even if we impl nested-routes that way, having both options available is good.

**Comment by pateketrueke** [comment]
FTR; I found a nice way to solve nested-routes and such, I'll be working on this PR to solve that thing once at all! 🔥

**Comment by kazzkiq** [comment]
Awesome! Following it!

**Comment by pateketrueke** [comment]
> I also believe that all solutions hash-based routes solve are also solved by nested routes, so they will be eventually replaced even if we implement them now.

FTR: your comment motivated me to find a proper solution for these issues, cheers! 🥂

**Comment by tehpsalmist** [comment]
Is there anything in particular holding this up? I need some of these features and don't want to reinvent the wheel if I don't have to. I'm pulling this branch into my current project to test it out in the meantime. I'll report back any bugs I run into.

**Comment by tehpsalmist** [comment]
@pateketrueke `path="*"` doesn't work anymore. It won't load my component at all.

```
<Router>
      <Route path="/workspaces/:id" component={Workspace} />
      <Route path="/new_workspace" component={CreateWorkspace} />
      <Route path="*" {workspaces} component={Home} />
</Router>
```
I put the star route at the top and bottom of the route list, same result either way.

**Comment by pateketrueke** [comment]
@tehpsalmist yeah, the meaning of `*` changed: it will serve as fallback only in case no other routes were matched.

In your case, an **exact** path to `/` should deal with:

```
<Router>
      <Route path="/workspaces/:id" component={Workspace} />
      <Route path="/new_workspace" component={CreateWorkspace} />
      <Route exact path="/" {workspaces} component={Home} />
      <Route path="*">Route not found!</Route>
</Router>
```

IMHO I don't _feel right_ using `*` to match a `Home` component, it means more a catch-all to me.

**Comment by tehpsalmist** [comment]
Yeah, I found that using `exact fallback path="/"` worked for me, but I have an assumption that if a fallback happens, then the url should be rewritten (history.replaceState?) to reflect the route that was redirected to. Maybe I should use a redirect then...

This has been an interesting experiment.

**Comment by pateketrueke** [comment]
> @kazzkiq any thoughts? 🤔

**Comment by kazzkiq** [comment]
Ok finally got some time to fiddle with this PR. Very nice work!

Since this has some breaking changes (such as `*` behavior) I will release a major version out of it.

**Comment by urosgruber** [comment]
@pateketrueke nice work. I have a question though. Now that nesting of routes work would it work if inner routes are specified within a component. 

App.svelte
```
<Router>
      <Route path="/news" component={News} />
</Router>
```

News.sevlte
```
<Router>
      <Route path="/:id" component={NewsDetail} />
</Router>
```

So to access details with path `/news/13`

**Comment by pateketrueke** [comment]
Hi @urosgruber currently `<Router />` components does not have a way to know which path is used from top-level routes, to make your example work you must add `path` to the inner `<Router />` in order to pass that info.

```html
<Router path="/news">
	<Route path="/:id" component={NewsDetail} />
</Router>
```

However this is just a temporary workaround, I believe we can fix that stuff soon, but atm is not a deal-breaker.

Or if it is, let us know.

Thank you!

**Pull request merged**
